# Generated by Django 4.2 on 2023-04-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='rate',
        ),
        migrations.AddField(
            model_name='subject',
            name='rate',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
